import type { PageLoad } from './$types';
import AandW from '$lib/assets/stores/a&w-1.avif';
import McDonalds from '$lib/assets/stores/mcdonalds-1.webp';
import Wendys from '$lib/assets/stores/wendys-1.jpg';
import Perrogies from '$lib/assets/stores/perrogies-1.jpg';
import PizzaPizza from '$lib/assets/stores/pizza-pizza-1.avif';
import { arrangeDeals } from '$lib/features/deals/deal-carousel/utils/arrange-deals.js';
import type { Deal } from '$lib/entities/deal';
export const load: PageLoad = () => {
    const deals: Deal[] = [
        {
            name: 'Buy One Get One Free',
            distance: 1.1,
            image: { src: AandW, alt: 'A&W food' },
            storeName: 'A&W',
            savedPercentage: 4,
            link: 'https://www.aw.ca/en/home',
            category: ['Trending Now', 'Deals Near You'],
        },
        {
            name: '20% Off Pizza',
            distance: 2.2,
            image: { src: PizzaPizza, alt: 'Pizza Pizza food' },
            storeName: 'Pizza Pizza',
            savedPercentage: 20,
            link: 'https://www.pizzapizza.ca/',
            category: ['Trending Now', 'Pizza Picks', 'Mega Savings'],
        },
        {
            name: 'Free Drink with Meal',
            distance: 0.8,
            image: { src: McDonalds, alt: 'McDonalds food' },
            storeName: 'McDonalds',
            savedPercentage: 5,
            link: 'https://www.mcdonalds.com/',
            category: ['Trending Now', 'Deals Near You'],
        },
        {
            name: 'Half Price Perogies',
            distance: 1.5,
            image: { src: Perrogies, alt: 'Perrogies' },
            storeName: 'Perrogies Place',
            savedPercentage: 50,
            link: 'https://www.perrogiesplace.com/',
            category: ['Trending Now', 'Mega Savings', 'Limited Time Offers'],
        },
        {
            name: 'Buy One Get One Free Burger',
            distance: 2.0,
            image: { src: Wendys, alt: 'Wendys food' },
            storeName: 'Wendys',
            savedPercentage: 10,
            link: 'https://www.wendys.com/',
            category: ['Trending Now', 'Deals Near You', 'Limited Time Offers'],
        },
        {
            name: 'Half Price Pizza',
            distance: 3.1,
            image: { src: PizzaPizza, alt: 'Pizza Pizza food' },
            storeName: 'Pizza Pizza',
            savedPercentage: 50,
            link: 'https://www.pizzapizza.ca/',
            category: ['Pizza Picks', 'Mega Savings'],
        },
        {
            name: '2 Large Pizzas for $20',
            distance: 4.0,
            image: { src: PizzaPizza, alt: 'Pizza Pizza food' },
            storeName: 'Pizza Pizza',
            savedPercentage: 15,
            link: 'https://www.pizzapizza.ca/',
            category: ['Pizza Picks', 'Limited Time Offers'],
        },
        {
            name: 'Free Breadsticks with Any Pizza',
            distance: 1.7,
            image: { src: PizzaPizza, alt: 'Pizza Pizza food' },
            storeName: 'Pizza Pizza',
            savedPercentage: 10,
            link: 'https://www.pizzapizza.ca/',
            category: ['Pizza Picks', 'Mega Savings', 'Deals Near You'],
        },
        {
            name: 'Free Delivery on Orders Over $30',
            distance: 2.4,
            image: { src: PizzaPizza, alt: 'Pizza Pizza food' },
            storeName: 'Pizza Pizza',
            savedPercentage: 0,
            link: 'https://www.pizzapizza.ca/',
            category: ['Pizza Picks', 'Mega Savings'],
        },
        {
            name: 'Large 3-Topping Pizza for $12',
            distance: 3.3,
            image: { src: PizzaPizza, alt: 'Pizza Pizza food' },
            storeName: 'Pizza Pizza',
            savedPercentage: 20,
            link: 'https://www.pizzapizza.ca/',
            category: ['Pizza Picks', 'Mega Savings', 'Trending Now'],
        },
        {
            name: '50% Off Burgers',
            distance: 0.5,
            image: { src: AandW, alt: 'A&W food' },
            storeName: 'A&W',
            savedPercentage: 50,
            link: 'https://www.aw.ca/en/home',
            category: ['Deals Near You', 'Mega Savings'],
        },
        {
            name: 'Free Fries with Any Combo',
            distance: 0.3,
            image: { src: McDonalds, alt: 'McDonalds food' },
            storeName: 'McDonalds',
            savedPercentage: 15,
            link: 'https://www.mcdonalds.com/',
            category: ['Trending Now', 'Deals Near You', 'Limited Time Offers'],
        },
        {
            name: 'Discounted Kids Meals',
            distance: 2.5,
            image: { src: McDonalds, alt: 'McDonalds food' },
            storeName: 'McDonalds',
            savedPercentage: 10,
            link: 'https://www.mcdonalds.com/',
            category: ['Deals Near You', 'Trending Now', 'Mega Savings'],
        },
        {
            name: 'Free Dessert with Entree',
            distance: 1.9,
            image: { src: Wendys, alt: 'Wendys food' },
            storeName: 'Wendys',
            savedPercentage: 20,
            link: 'https://www.wendys.com/',
            category: ['Limited Time Offers', 'Deals Near You'],
        },
        {
            name: '30% Off Family Meals',
            distance: 3.6,
            image: { src: Wendys, alt: 'Wendys food' },
            storeName: 'Wendys',
            savedPercentage: 30,
            link: 'https://www.wendys.com/',
            category: ['Trending Now', 'Mega Savings'],
        },
        {
            name: 'Buy One Pasta, Get One 50% Off',
            distance: 2.8,
            image: { src: Wendys, alt: 'Wendys food' },
            storeName: 'Wendys',
            savedPercentage: 50,
            link: 'https://www.wendys.com/',
            category: ['Mega Savings', 'Trending Now'],
        },
        {
            name: '25% Off Breakfast Combos',
            distance: 1.4,
            image: { src: McDonalds, alt: 'McDonalds food' },
            storeName: 'McDonalds',
            savedPercentage: 25,
            link: 'https://www.mcdonalds.com/',
            category: ['Trending Now', 'Deals Near You', 'Limited Time Offers'],
        },
        {
            name: 'Large Coffee for $1',
            distance: 0.9,
            image: { src: McDonalds, alt: 'McDonalds food' },
            storeName: 'McDonalds',
            savedPercentage: 15,
            link: 'https://www.mcdonalds.com/',
            category: ['Deals Near You', 'Limited Time Offers'],
        },
        {
            name: 'Free Kids Drink with Meal',
            distance: 3.0,
            image: { src: AandW, alt: 'A&W food' },
            storeName: 'A&W',
            savedPercentage: 10,
            link: 'https://www.aw.ca/en/home',
            category: ['Trending Now', 'Deals Near You'],
        },
        {
            name: 'Two Sandwiches for $5',
            distance: 1.8,
            image: { src: Wendys, alt: 'Wendys food' },
            storeName: 'Wendys',
            savedPercentage: 40,
            link: 'https://www.wendys.com/',
            category: ['Mega Savings', 'Limited Time Offers'],
        },
        {
            name: 'Unlimited Toppings for Free',
            distance: 2.3,
            image: { src: PizzaPizza, alt: 'Pizza Pizza food' },
            storeName: 'Pizza Pizza',
            savedPercentage: 20,
            link: 'https://www.pizzapizza.ca/',
            category: ['Pizza Picks', 'Mega Savings', 'Trending Now'],
        },
        {
            name: 'All You Can Eat for $15',
            distance: 2.7,
            image: { src: Perrogies, alt: 'Perrogies' },
            storeName: 'Perrogies Place',
            savedPercentage: 30,
            link: 'https://www.perrogiesplace.com/',
            category: ['Mega Savings', 'Trending Now', 'Limited Time Offers'],
        },
        {
            name: 'Free Appetizer with Main Course',
            distance: 1.2,
            image: { src: McDonalds, alt: 'McDonalds food' },
            storeName: 'McDonalds',
            savedPercentage: 10,
            link: 'https://www.mcdonalds.com/',
            category: ['Deals Near You', 'Trending Now'],
        },
        {
            name: 'Happy Hour Discounts',
            distance: 3.2,
            image: { src: AandW, alt: 'A&W food' },
            storeName: 'A&W',
            savedPercentage: 25,
            link: 'https://www.aw.ca/en/home',
            category: ['Trending Now', 'Limited Time Offers'],
        },
        {
            name: 'Half Off on Second Pizza',
            distance: 2.9,
            image: { src: PizzaPizza, alt: 'Pizza Pizza food' },
            storeName: 'Pizza Pizza',
            savedPercentage: 50,
            link: 'https://www.pizzapizza.ca/',
            category: ['Pizza Picks', 'Mega Savings'],
        },
        {
            name: 'Combo Meals for $9',
            distance: 1.6,
            image: { src: Wendys, alt: 'Wendys food' },
            storeName: 'Wendys',
            savedPercentage: 20,
            link: 'https://www.wendys.com/',
            category: ['Trending Now', 'Deals Near You', 'Limited Time Offers'],
        },
        {
            name: '2-for-1 Milkshakes',
            distance: 0.7,
            image: { src: AandW, alt: 'A&W food' },
            storeName: 'A&W',
            savedPercentage: 50,
            link: 'https://www.aw.ca/en/home',
            category: ['Deals Near You', 'Limited Time Offers'],
        },
        {
            name: 'Flat 30% Off Orders Above $50',
            distance: 4.1,
            image: { src: Perrogies, alt: 'Perrogies' },
            storeName: 'Perrogies Place',
            savedPercentage: 30,
            link: 'https://www.perrogiesplace.com/',
            category: ['Mega Savings', 'Limited Time Offers'],
        },
        {
            name: 'Late Night Pizza Discounts',
            distance: 3.5,
            image: { src: PizzaPizza, alt: 'Pizza Pizza food' },
            storeName: 'Pizza Pizza',
            savedPercentage: 20,
            link: 'https://www.pizzapizza.ca/',
            category: ['Pizza Picks', 'Deals Near You', 'Trending Now'],
        },
        {
            name: 'Discounted Party Platters',
            distance: 2.1,
            image: { src: McDonalds, alt: 'McDonalds food' },
            storeName: 'McDonalds',
            savedPercentage: 25,
            link: 'https://www.mcdonalds.com/',
            category: ['Trending Now', 'Mega Savings'],
        },
        {
            name: 'Breakfast Combos for $5',
            distance: 0.6,
            image: { src: McDonalds, alt: 'McDonalds food' },
            storeName: 'McDonalds',
            savedPercentage: 35,
            link: 'https://www.mcdonalds.com/',
            category: ['Deals Near You', 'Trending Now', 'Limited Time Offers'],
        },
        {
            name: 'Kids Eat Free Sundays',
            distance: 2.4,
            image: { src: AandW, alt: 'A&W food' },
            storeName: 'A&W',
            savedPercentage: 100,
            link: 'https://www.aw.ca/en/home',
            category: ['Trending Now', 'Limited Time Offers'],
        },
        {
            name: 'Large Drinks for $1',
            distance: 0.2,
            image: { src: Wendys, alt: 'Wendys food' },
            storeName: 'Wendys',
            savedPercentage: 50,
            link: 'https://www.wendys.com/',
            category: ['Deals Near You', 'Limited Time Offers'],
        },
    ];
    const arragnedDeals = arrangeDeals(deals)
    return arragnedDeals
};